query FetchProfilePage($userID: ID!) {
  getUser(id: $userID) {
    pictureURL
    rating
    name
    email
    location
    phoneNumber
    projects {
      items {
        id
        photos
        averageBidAmount
        title
        tags
        chosenBid {
          id
        }
      }
    }
  }
}
