query FetchPlaceBid($projID: ID!) {
  getProject(id: $projID) {
    owner {
      name
      rating
    }
    
    timeUntilClose
    numberOfBids
    averageBidAmount
    photos
    description
    
  }
  
  
  
}
